# Generated by Django 6.0.6 on 2026-07-12 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='berita',
            name='gambar',
            field=models.ImageField(blank=True, null=True, upload_to='gambar/berita/'),
        ),
    ]
